### ISSUE TITLE
`assembleAffectedAndroidTests` assembles APKs for all modules

### ISSUE THREAD

**Issue by ilynehan** [dropbox/AffectedModuleDetector#66] opened 2021-08-11 21:10 UTC
Hello!

I am running into an issue where calling
```
gradle assembleAffectedAndroidTests -Paffected_module_detector.enabled
```
assembles the APKs for all modules.

Based on the documentation, I am under the assumption that this task should generate test apks for **_only_** the affected module(s). 

Here are the configurations I have set up:
```
affectedModuleDetector {
    baseDir = "${project.rootDir}"
    logFolder = "${project.rootDir}/artifacts"
    specifiedBranch = "${base_branch}"
    compareFrom = 'SpecifiedBranchCommit'
}

affectedTestConfiguration {
    assembleAndroidTestTask = 'assembleStandardDebugAndroidTest'
    runAndroidTestTask = 'assembleStandardDebugAndroidTest'
    jvmTestTask = 'testStandardDebugUnitTest'
}
```

Cross-referencing the logs and the apk output, I see that
```
[INFO] [amd] checking whether I should include :lib:featuretoggle and my answer is false
```
but 
```
./lib/featuretoggle/build/outputs/apk/androidTest/standard/debug/featuretoggle-standard-debug-androidTest.apk
```
 is still being generated.

Please let me know if this is the expected behavior or if I am doing something wrong. Thank you!

**Comment by wclausen** [comment] 2022-02-07 17:52
@ilynehan can you provide more information about your project setup or a sample that reproduces the issue? It could be generating all the apks for a few reasons. One that seems plausible here is that you changed something in a module that the feature toggle depends on. If you changed a base module, then the affected module detector would determine that the feature module is affected through its dependency on the base module and assemble its test apk. In this case, if you wanted to only have the base module be built, you would want to specify that only changed projects should run using `-Paffected_module_detector.changedProjects`. The default is to include dependent projects in addition to changed projects.

**Comment by joshafeinberg** [comment] 2022-04-13 20:05
Hello @ilynehan - I'm going to close this as there hasn't been an update since last August. Please let us know if this is still an issue and if so can you please do as Will asked and either provide a sample or some more details.

**Closed by joshafeinberg** 2022-04-13 20:05 UTC
