### ISSUE TITLE
Task '.enable' not found in root project 'my-multi-module-project'.

### ISSUE THREAD

**Issue by mklueh** [dropbox/AffectedModuleDetector#141] opened 2022-05-09 17:46 UTC
I'm not able to use this plugin like described as I'm running into the issue from the title as soon as the parameters are attached to my gradle command.

this is my root build.gradle

```
plugins {
    id "com.dropbox.affectedmoduledetector" version "0.1.5"
}

apply plugin: 'java'
apply plugin: 'idea'

affectedModuleDetector {
    baseDir = "${project.rootDir}"
    pathsAffectingAllModules = []
    logFolder = "${project.rootDir}/tools/impact-analysis/output"
    specifiedBranch = "reactive"
    compareFrom = "SpecifiedBranchCommit"
    includeUncommitted = false
}
```

settings.gradle

```
pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    plugins {
        id "${quarkusPluginId}" version "${quarkusPluginVersion}"
        id "com.nike.pdm.localstack" version "1.0.0"
    }
}
```

The logs
```
PS C:\Users\My-PC\Workspace\my-multi-module-project> ./gradlew build -Paffected_module_detector.enable                 

Welcome to Gradle 7.4.2!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.2/release-notes.html


FAILURE: Build failed with an exception.

* What went wrong:
Task '.enable' not found in root project 'my-multi-module-project'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
PS C:\Users\My-PC\Workspace\my-multi-module-project> 

```

What am I missing?

**Comment by Evleaps** [comment] 2022-05-15 18:50
Hello! I tried to reproduce your issue and I see that you are using Windows. 

Unfortunately, AMD doesn't support Windows right now. In actual fact, I successfully reproduced your issue on my Windows PC but it works correctly on my Mac OS laptop. 

Your issue is the same as [another already opened issue](https://github.com/dropbox/AffectedModuleDetector/issues/37

Anyway, it might be helpful for the debugging. 

@joshafeinberg @chris-mitchell FYI

**Comment by mklueh** [comment] 2022-05-15 19:06
Hey @Evleaps , thanks.

I've stumbled across this issue with a similar plugin and the author helped me https://github.com/Crimix/ChangedProjectsTaskPlugin/issues/2#issuecomment-1126881620

Haven't tried it with this plugin, but its likely a PowerShell issue and can be fixed b putting the parameter in "quotation marks"

**Comment by joshafeinberg** [comment] 2022-07-08 15:21
Yes, closing this a duplicate of #37. Happy to accept PRs to fix this but we currently do not use windows machines so unknown when we will have a chance to fix. Don't see a need to put this in the readme either as one can confirm in the issues and this seems to be lightly reported

**Closed by joshafeinberg** 2022-07-08 15:21 UTC
